- name: Deploy frontend and backend containers from GitHub
  hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/prakashanand084/3t-project.git"
    app_path: "/root/anand/"
    frontend_image: "frontend-app:latest"
    backend_image: "backend-app:latest"
    rds_host: "database-1.ch6q2sygelek.us-east-1.rds.amazonaws.com"
    rds_user: "admin"
    rds_password: "Cloud123"
    rds_port: "3306"

  roles:
    - common
    - gitclone
    - frontend
    - backend

