- name: Build backend Docker image
  docker_image:
    name: "{{ backend_image }}"
    source: build
    build:
      path: "{{ app_path }}/backend"

- name: Run backend container with RDS credentials
  docker_container:
    name: backend
    image: "{{ backend_image }}"
    state: started
    env:
      DB_HOST: "{{ rds_host }}"
      DB_USERNAME: "{{ rds_user }}"
      DB_PASSWORD: "{{ rds_password }}"
      PORT: "{{ rds_port }}"
    ports:
      - "84:80"
    restart_policy: always
